name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint_typecheck_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: '9'
          run_install: true
          cache: true

      - name: Prettier format check
        run: pnpm run format:check

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint
